### ISSUE TITLE
latest release

### ISSUE THREAD

**Issue by MeinDeutschkurs** [Shakshi3104/LiTeX#4]
Mac OS denies execution, because "it's not possible to check the software on malware". I try to compile it with Xcode. Ventura 13.4 (22F66), M1-max

**Comment by MeinDeutschkurs** [comment]
I can confirm, that it works after compiling. Xcode updated several things by its own. Cannot check it, I have no idea what I did in Xcode. 🤣 - But it worked.

**Comment by rainyskye** [comment]
The issue is mostly likely just because it's not notarized by Apple, see https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution

You can get around it usually by right clicking the pressing `Open` on the executable and allowing it to run at least once that way, then it will launch fine consecutively, you can also disable Gatekeeper but that's not recommended.

PS: if you've fixed the issue, closing the issue is a good idea :)

**Comment by MeinDeutschkurs** [comment]
Thank you very much for the notice. Before the latest Ventura update, there were no issues.
